THIS HAS ALREADY BEEN RUN!

In [89]:
import pandas as pd
original = pd.read_excel("/Users/mlaurencechen/Library/CloudStorage/OneDrive-CornellUniversity/Internships/Projects/FPL ML 2/Data/FPL_Player_Data_SeasonUntil2024.xlsx")
original

,Unnamed: 0,Index,ID,Name,Game Name,Team,Position,Current Price,2022/23 Season Points,2022/23 Season Minutes,...,2008/09 Season Goals,2008/09 Season Assists,2008/09 Season YC,2008/09 Season RC,2008/09 Season Saves,2008/09 Season Penalty Saves,2008/09 Season OG,2008/09 Season Penalty Misses,2008/09 Season CS,2008/09 Season GC
0,0,1,1,Fábio Ferreira Vieira,Fábio Vieira,Arsenal,MID,5.5,40.0,500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,2,2,Gabriel Fernando de Jesus,G.Jesus,Arsenal,FWD,7.0,125.0,2064.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,3,3,Gabriel dos Santos Magalhães,Gabriel,Arsenal,DEF,6.0,146.0,3409.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,4,4,Kai Havertz,Havertz,Arsenal,FWD,8.0,102.0,2565.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,5,5,Karl Hein,Hein,Arsenal,GKP,4.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
589,0,590,563,Rodrigo Martins Gomes,R.Gomes,Wolverhampton_Wanderers,MID,5.5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590,0,591,564,Santiago Bueno,S.Bueno,Wolverhampton_Wanderers,DEF,4.5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
591,0,592,565,Pablo Sarabia,Sarabia,Wolverhampton_Wanderers,MID,5.5,27.0,764.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
592,0,593,566,Jørgen Strand Larsen,Strand Larsen,Wolverhampton_Wanderers,FWD,5.5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
593,0,594,567,Toti António Gomes,Toti,Wolverhampton_Wanderers,DEF,4.5,43.0,978.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
prefix = "Season"
column_names = ["Points", "Minutes", "I", "C", "T", "Bonus", "Bonus Points", "Beginning Price", "End Price", "Goals", "Assists", "YC", "RC", "Saves", "Penalty Saves", "OG", "Penalty Misses", "CS", "GC"]
df_columns = ["Position", "Feature Year", "Target Points"] + column_names

new_df = pd.DataFrame(columns= df_columns)

new_df

Empty DataFrame
Columns: [Position, Feature Year, Target Points, Points, Minutes, I, C, T, Bonus, Bonus Points, Beginning Price, End Price, Goals, Assists, YC, RC, Saves, Penalty Saves, OG, Penalty Misses, CS, GC]
Index: []

[0 rows x 22 columns]

In [74]:
def increment_year(year: str) -> str:
    new_year = str(int(year) + 1)
    if (int(new_year) < 10):
        new_year = "0" + new_year
    return new_year

print(increment_year("6"))

07

In [90]:
first_year = "08"
end_year = "23"
current_year = first_year
curr_dfs = []
while int(current_year) != int(end_year):
    print(current_year)
    next_year = increment_year(current_year)
    next_next_year = increment_year(next_year)
    feature_prefix = "20" + current_year + "/" + next_year + " Season "
    target_prefix = "20" + next_year + "/" + next_next_year + " Season "
    for index, row in original.iterrows():
        curr_target_points = row[target_prefix + "Points"]
        if not pd.notna(curr_target_points):
            continue
        position = row["Position"]
        curr_features = [position ,current_year, curr_target_points]
        for feature in column_names:
            feature_name = feature_prefix + feature
            curr_features.append(row[feature_name])
        curr_df = pd.DataFrame([curr_features], columns = df_columns)
        curr_dfs.append(curr_df)
    current_year = increment_year(current_year)

new_df = pd.concat(curr_dfs)
new_df = new_df.dropna()
new_df

08
09
10
11
12
13
14
15
16
17
18
19
20
21
22

,Position,Feature Year,Target Points,Points,Minutes,I,C,T,Bonus,Bonus Points,...,Goals,Assists,YC,RC,Saves,Penalty Saves,OG,Penalty Misses,CS,GC
0,MID,08,184.0,128.0,3060.0,0.0,0.0,0.0,0.0,7.0,...,3.0,9.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,36.0
0,FWD,08,6.0,9.0,118.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0,DEF,08,152.0,153.0,3190.0,0.0,0.0,0.0,0.0,20.0,...,7.0,9.0,7.0,1.0,0.0,0.0,0.0,1.0,0.0,47.0
0,DEF,08,68.0,73.0,1422.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0
0,GKP,08,15.0,20.0,463.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,18.0,0.0,0.0,0.0,0.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,DEF,22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0,DEF,22,63.0,75.0,2633.0,455.0,229.4,88.0,424.0,5.0,...,0.0,1.0,11.0,1.0,0.0,0.0,0.0,0.0,8.0,43.0
0,MID,22,0.0,92.0,1760.0,376.0,512.8,580.0,249.0,10.0,...,6.0,1.0,5.0,0.0,0.0,0.0,0.0,0.0,6.0,31.0
0,MID,22,99.0,27.0,764.0,92.0,184.7,157.0,57.0,3.0,...,1.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,3.0,9.0
0,DEF,22,82.0,43.0,978.0,230.0,74.5,69.0,201.0,4.0,...,1.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,4.0,14.0

In [70]:
new_df.to_excel("FPL_Cleaned_By_Position_Until_2021.xlsx")

In [93]:
original = pd.read_excel("/Users/mlaurencechen/Library/CloudStorage/OneDrive-CornellUniversity/Internships/Projects/FPL ML 2/Data/FPL_Cleaned_By_Position_Until_2021.xlsx")
original

,Unnamed: 0,Position,Feature Year,Target Points,Points,Minutes,I,C,T,Bonus,...,Goals,Assists,YC,RC,Saves,Penalty Saves,OG,Penalty Misses,CS,GC
0,0,DEF,6,177,134,2780,0.0,0.0,0,0,...,5,6,3,0,0,0,0,0,0,38
1,0,GKP,6,41,0,0,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,MID,6,84,114,2675,0.0,0.0,0,0,...,3,7,3,0,0,0,0,0,0,37
3,0,GKP,6,113,139,3240,0.0,0.0,0,0,...,0,1,1,0,117,2,0,0,0,55
4,0,FWD,6,283,244,2783,0.0,0.0,0,0,...,17,16,2,0,0,0,0,1,0,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1553,0,DEF,20,87,54,1400,243.2,234.5,196,264,...,1,1,1,0,0,0,0,0,3,23
1554,0,FWD,20,30,72,1352,238.2,166.1,758,198,...,4,3,2,0,0,0,0,0,0,29
1555,0,MID,20,44,94,2640,475.4,751.0,645,359,...,2,4,4,0,0,0,0,0,7,41
1556,0,MID,20,96,73,2526,478.4,726.9,113,446,...,1,1,3,1,0,0,0,0,6,40
1557,0,DEF,20,0,0,0,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [94]:
original

,Unnamed: 0,Position,Feature Year,Target Points,Points,Minutes,I,C,T,Bonus,...,Goals,Assists,YC,RC,Saves,Penalty Saves,OG,Penalty Misses,CS,GC
0,0,DEF,6,177,134,2780,0.0,0.0,0,0,...,5,6,3,0,0,0,0,0,0,38
1,0,GKP,6,41,0,0,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,MID,6,84,114,2675,0.0,0.0,0,0,...,3,7,3,0,0,0,0,0,0,37
3,0,GKP,6,113,139,3240,0.0,0.0,0,0,...,0,1,1,0,117,2,0,0,0,55
4,0,FWD,6,283,244,2783,0.0,0.0,0,0,...,17,16,2,0,0,0,0,1,0,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1553,0,DEF,20,87,54,1400,243.2,234.5,196,264,...,1,1,1,0,0,0,0,0,3,23
1554,0,FWD,20,30,72,1352,238.2,166.1,758,198,...,4,3,2,0,0,0,0,0,0,29
1555,0,MID,20,44,94,2640,475.4,751.0,645,359,...,2,4,4,0,0,0,0,0,7,41
1556,0,MID,20,96,73,2526,478.4,726.9,113,446,...,1,1,3,1,0,0,0,0,6,40
1557,0,DEF,20,0,0,0,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [108]:
merged_df = pd.concat([original, new_df])
print(merged_df.columns)
merged_df = merged_df.drop('Unnamed: 0', axis=1)
merged_df = merged_df.reset_index(drop=True)
merged_df

Index(['Unnamed: 0', 'Position', 'Feature Year', 'Target Points', 'Points',
       'Minutes', 'I', 'C', 'T', 'Bonus', 'Bonus Points', 'Beginning Price',
       'End Price', 'Goals', 'Assists', 'YC', 'RC', 'Saves', 'Penalty Saves',
       'OG', 'Penalty Misses', 'CS', 'GC'],
      dtype='object')

,Position,Feature Year,Target Points,Points,Minutes,I,C,T,Bonus,Bonus Points,...,Goals,Assists,YC,RC,Saves,Penalty Saves,OG,Penalty Misses,CS,GC
0,DEF,6,177.0,134.0,2780.0,0.0,0.0,0.0,0.0,20.0,...,5.0,6.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,38.0
1,GKP,6,41.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,MID,6,84.0,114.0,2675.0,0.0,0.0,0.0,0.0,11.0,...,3.0,7.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,37.0
3,GKP,6,113.0,139.0,3240.0,0.0,0.0,0.0,0.0,4.0,...,0.0,1.0,1.0,0.0,117.0,2.0,0.0,0.0,0.0,55.0
4,FWD,6,283.0,244.0,2783.0,0.0,0.0,0.0,0.0,36.0,...,17.0,16.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3066,DEF,22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3067,DEF,22,63.0,75.0,2633.0,455.0,229.4,88.0,424.0,5.0,...,0.0,1.0,11.0,1.0,0.0,0.0,0.0,0.0,8.0,43.0
3068,MID,22,0.0,92.0,1760.0,376.0,512.8,580.0,249.0,10.0,...,6.0,1.0,5.0,0.0,0.0,0.0,0.0,0.0,6.0,31.0
3069,MID,22,99.0,27.0,764.0,92.0,184.7,157.0,57.0,3.0,...,1.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,3.0,9.0
3070,DEF,22,82.0,43.0,978.0,230.0,74.5,69.0,201.0,4.0,...,1.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,4.0,14.0

In [109]:
new = merged_df.drop_duplicates()
new

,Position,Feature Year,Target Points,Points,Minutes,I,C,T,Bonus,Bonus Points,...,Goals,Assists,YC,RC,Saves,Penalty Saves,OG,Penalty Misses,CS,GC
0,DEF,6,177.0,134.0,2780.0,0.0,0.0,0.0,0.0,20.0,...,5.0,6.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,38.0
1,GKP,6,41.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,MID,6,84.0,114.0,2675.0,0.0,0.0,0.0,0.0,11.0,...,3.0,7.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,37.0
3,GKP,6,113.0,139.0,3240.0,0.0,0.0,0.0,0.0,4.0,...,0.0,1.0,1.0,0.0,117.0,2.0,0.0,0.0,0.0,55.0
4,FWD,6,283.0,244.0,2783.0,0.0,0.0,0.0,0.0,36.0,...,17.0,16.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3066,DEF,22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3067,DEF,22,63.0,75.0,2633.0,455.0,229.4,88.0,424.0,5.0,...,0.0,1.0,11.0,1.0,0.0,0.0,0.0,0.0,8.0,43.0
3068,MID,22,0.0,92.0,1760.0,376.0,512.8,580.0,249.0,10.0,...,6.0,1.0,5.0,0.0,0.0,0.0,0.0,0.0,6.0,31.0
3069,MID,22,99.0,27.0,764.0,92.0,184.7,157.0,57.0,3.0,...,1.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,3.0,9.0
3070,DEF,22,82.0,43.0,978.0,230.0,74.5,69.0,201.0,4.0,...,1.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,4.0,14.0

In [110]:
new.to_excel("FPL_Cleaned_By_Position_Until_2024.xlsx")